name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Restore dependencies from cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            common/temp/pnpm-store
            $HOME/.rush
          key: ${{ runner.os }}-${{ hashFiles('config/rush/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install missing dependencies
        run: node ./common/scripts/install-run-rush.js install
      - name: Compile packages
        run: node ./common/scripts/install-run-rush.js build
        env:
          ELECTRON_WEBPACK_APP_API_ROOT: ${{ secrets.API_ROOT }}
          ELECTRON_WEBPACK_APP_DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      - name: Run unit tests
        working-directory: ./tools/toolchain
        run: |
          ./node_modules/.bin/jest --config ./jest.monorepo.config.js --passWithNoTests
        env:
          CI: "true"
      - name: Bump version (master -> beta)
        if: ${{ github.ref == 'refs/heads/master' }}
        working-directory: ./app/desktop
        run: yarn version --prerelease --preid beta.$(git rev-parse --short HEAD) --no-git-tag-version
      - name: Bump version (pull_request -> alpha)
        if: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/desktop-v')}}
        working-directory: ./app/desktop
        run: yarn version --prerelease --preid alpha.$(git rev-parse --short HEAD) --no-git-tag-version
      - name: Package desktop app installer
        working-directory: ./app/desktop
        run: npm run package -- --publish onTagOrDraft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload desktop app installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: app/desktop/dist/*.exe
